version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8880:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        build: ./
        restart: always
        volumes:
            - ./code:/code
    mysql:
      image: mysql:5.7
      ports:
        - "3307:3306"
      environment:
        - MYSQL_DATABASE=thuctapPHP
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=root 
      volumes:
          - ./code:/code