version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./code/crud_mvc_php/Views:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        restart: always
        volumes:
            - ./code/crud_mvc_php/Views:/code
        networks:
            - code-network
    mysql:
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=thuctapphp
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
      volumes:
          - ./code/mvc-composer/app:/code
networks:
    code-network:
        driver: bridge